# Generated by Django 4.2.1 on 2023-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone2',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles'),
        ),
    ]
