# Generated by Django 4.2.1 on 2023-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_phone2_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(default='profiles/default.webp', upload_to='profiles'),
        ),
    ]
