# Generated by Django 4.2.1 on 2023-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles'),
        ),
    ]
