# Generated by Django 4.2.1 on 2023-06-09 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('CurrResidence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'Art'), ('S', 'Sport'), ('SC', 'Sciences'), ('C', 'Club')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50)),
                ('start_academic_year', models.CharField(max_length=50)),
                ('end_academic_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='crcprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Studie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('scholarship', models.CharField(choices=[('F', 'Full'), ('P', 'Partial'), ('N', 'None')], max_length=2)),
                ('status', models.CharField(choices=[('D', 'Dropped_Out'), ('S', 'Susepended'), ('C', 'Completed')], max_length=2)),
                ('alumn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studie', to='userprofile.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('family_number', models.IntegerField(blank=True, null=True)),
                ('family_mother', models.CharField(blank=True, default='', max_length=200)),
                ('family_mother_tel', models.CharField(blank=True, default='', max_length=200)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='userprofile.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('W', 'working'), ('P', 'past')], max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=50)),
                ('alumn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emproyement', to='userprofile.alumni')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='Combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnis', to='userprofile.combination'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Eps',
            field=models.ManyToManyField(blank=True, related_name='alumnis', to='userprofile.ep'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnis', to='userprofile.family'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumn', to=settings.AUTH_USER_MODEL),
        ),
    ]
