# Generated by Django 4.2.1 on 2023-06-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_crcprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'Art'), ('S', 'Sport'), ('SC', 'Sciences'), ('C', 'Club')], max_length=2)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50)),
                ('start_academic_year', models.CharField(max_length=50)),
                ('end_academic_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('family_number', models.IntegerField(blank=True, null=True)),
                ('family_mother', models.CharField(blank=True, default='', max_length=200)),
                ('family_mother_tel', models.CharField(blank=True, default='', max_length=200)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='userprofile.grade')),
            ],
        ),
    ]
