# Generated by Django 4.2.1 on 2023-06-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alumni_combination_ep_event_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('alumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='userprofile.alumni')),
            ],
        ),
    ]
