# Generated by Django 4.2.1 on 2023-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='end_date',
            field=models.CharField(default='Up to now', max_length=50),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employment',
            name='status',
            field=models.CharField(choices=[('F', 'Full-time'), ('P', 'Part-time'), ('S', 'Self-employed')], max_length=2),
        ),
    ]
