# Generated by Django 4.2.1 on 2023-06-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_combination_ep_grade_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combination',
            old_name='name',
            new_name='combination_name',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='created',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='ep',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ep',
            name='updated',
        ),
    ]
