# Generated by Django 4.2.1 on 2023-06-05 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_rename_name_combination_combination_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('CurrResidence', models.CharField(max_length=50)),
                ('Combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnis', to='userprofile.combination')),
                ('Eps', models.ManyToManyField(related_name='alumnis', to='userprofile.ep')),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnis', to='userprofile.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Studie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('scholarship', models.CharField(choices=[('F', 'Full'), ('P', 'Partial'), ('N', 'None')], max_length=2)),
                ('status', models.CharField(choices=[('D', 'Dropped_Out'), ('S', 'Susepended'), ('C', 'Completed')], max_length=2)),
                ('alumn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studie', to='userprofile.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
