# Generated by Django 4.2.1 on 2023-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_employment_end_date_employment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='status',
            field=models.CharField(choices=[('F', 'Full-time'), ('P', 'Part-time'), ('S', 'Self-employed'), ('I', 'Intern')], max_length=2),
        ),
    ]
