# Generated by Django 4.2.1 on 2023-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alumni_event_studie_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('W', 'working'), ('P', 'past')], max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='employments',
            field=models.ManyToManyField(related_name='employments', to='userprofile.employment'),
        ),
    ]
